# Generated by Django 5.2.1 on 2025-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interests",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="Main.interest"),
        ),
    ]
