# Generated by Django 5.2.1 on 2025-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(blank=True, default="Hello world!", max_length=255),
        ),
    ]
