# Generated by Django 5.2.1 on 2025-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_userprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="status",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="images/default-avatar.png",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
