# Generated by Django 5.2.1 on 2025-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_remove_userprofile_status_alter_userprofile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(blank=True, default="Hello world!", max_length=255),
        ),
    ]
